### ISSUE TITLE
Child or Parent Information Sidebar Features

### ISSUE THREAD

**Issue by n3m3sis00** [n3m3sis00/tree#15]
- [ ] Show some Calculated values[if possible]
- [ ] Show Sequence
- [ ] Show Siblings
- [ ] Visualize PDB Structure [from Ian's implementation]
- [ ] Separate Visualizer Buttons [ like synteny, etc]
...

**Comment by cmdcolin** [comment]
I would ideally focus on the "drawing extra information on the nodes" if possible similar to ians work

**Comment by cmdcolin** [comment]
Or really, ideally we want to make the tree drawing look good, and then we incorporate into jbrowse features for adding the extended drawing extra information on the nodes part

**Comment by cmdcolin** [comment]
I think at this point it might be outside the scope of this repo to add this, but it would play into a larger dashboard app. Maybe we close for now
