### ISSUE TITLE
Inconsistent spacing between nodes

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#16]
It would be good if all nodes basically had the same "height", but there are some places where there are extra spaces between nodes

![localhost_3000_](https://user-images.githubusercontent.com/6511937/85928792-bc6e7600-b87d-11ea-99d9-214fc65ede6b.png)

**Comment by n3m3sis00** [comment]
Have tried to incorporate equal spacing between the nodes.

### Screenshot
![Screenshot_2020-07-02 React App](https://user-images.githubusercontent.com/34513489/86357448-78b7aa00-bc8b-11ea-989d-3045b7ae886b.png)

**Comment by cmdcolin** [comment]
Looks great!
