### ISSUE TITLE
Calculate mapping of "species name->y-coordinate"

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#17]
For drawing extra data next to the species name, we need to know the Y-coordinate of that species name

Obtaining the "species name->y-coordinate" map is one idea, a possible other is drawing a more complex component instead of just species name, but I think that obtaining this coordinate map is the most straightforward option for now

**Comment by n3m3sis00** [comment]
Have tried to trace the coordinate map (Y-coordinate) of the species. 
### Screenshot 1

![metadata_1](https://user-images.githubusercontent.com/34513489/86780892-e2b0c480-c07a-11ea-9bbd-0aa541102f08.png)

### Screenshot 2
![metadata_2](https://user-images.githubusercontent.com/34513489/86780898-e47a8800-c07a-11ea-8453-930189b1056c.png)

**Comment by cmdcolin** [comment]
It looks like this was unneeded in a way, might close for now

**Comment by cmdcolin** [comment]
Or it got finished already,i forget :)
