### ISSUE TITLE
Example of sequence alignment->tree workflow

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#19]
https://github.com/YuLab-SMU/ggmsa#visualizing-multiple-sequence-alignment-with-ggtree

This is the type of workflow that would be nice to have

**Comment by cmdcolin** [comment]
Of course that is written in R but we can adapt to JS probably

**Comment by n3m3sis00** [comment]
## MSA Viewer 
I tried to build an MSA Viewer alongside Tree viewer

### Detailed Description
* MSA file: https://github.com/ihh/stockholm-js/blob/master/data/Lysine.stock, the sample file is also present in the data folder
* Tree: Tree is build using ClustalW https://www.ebi.ac.uk/Tools/phylogeny/simple_phylogeny/
    * Step 1: Copy MSA from MSA file
    * Step 2: Paste it in _Enter your multiple sequence alignment_ text box
    * Step 3: Submit the job
    * Step 4: Copy Newick formatted tree data from ClustalW.
Note: The tree for the above MSA is also present in the data folder.

#### How to Visualize
* Paste Tree in paste Newick tree textbox
* Paste MSA in paste sequence textbox
* Click Render


### TODO
* Color Coding
* MSA file Upload
* Reading tree and MSA from the same file

### Screenshot
![sequence_added](https://user-images.githubusercontent.com/34513489/87230182-ac9d7880-c3cb-11ea-9481-8a7c0a2ea1dd.png)

**Comment by cmdcolin** [comment]
Awesome!! Looks great

**Comment by n3m3sis00** [comment]
## Color Coding for Amino acids
```javascript
const lilac = "#C8A2C8"  // nonstandard
const colorScheme = {
  clustal: { G: "orange", P: "orange", S: "orange", T: "orange", H: "red", K: "red", R: "red", F: "blue", W: "blue", Y: "blue", I: "green", L: "green", M: "green", V: "green" },
  lesk: { G: "orange", A: "orange", S: "orange", T: "orange", C: "green", V: "green", I: "green", L: "green", P: "green", F: "green", Y: "green", M: "green", W: "green", N: "magenta", Q: "magenta", H: "magenta", D: "red", E: "red", K: "blue", R: "blue" },
  maeditor: { A: "lightgreen", G: "lightgreen", C: "green", D: "darkgreen", E: "darkgreen", N: "darkgreen", Q: "darkgreen", I: "blue", L: "blue", M: "blue", V: "blue", F: lilac, W: lilac, Y: lilac, H: "darkblue", K: "orange", R: "orange", P: "pink", S: "red", T: "red" },
  cinema: { H: "blue", K: "blue", R: "blue", D: "red", E: "red", S: "green", T: "green", N: "green", Q: "green", A: "white", V: "white", L: "white", I: "white", M: "white", F: "magenta", W: "magenta", Y: "magenta", P: "brown", G: "brown", C: "yellow", B: "gray", Z: "gray", X: "gray", "-": "white", ".": "white" }
}
```

note: These color codes are taken from Ian's repo.

* There are two type of visuals 
    * Bounding Box color code with white font color
    * No Bounding Box, font is the color code
Note: These can be toggled via switch in tool bar

### Screenshot
![Screenshot_2020-07-13 React App(1)](https://user-images.githubusercontent.com/36275145/87290622-d9f93c00-c51b-11ea-8412-c87067a9088a.png)
![Screenshot_2020-07-13 React App](https://user-images.githubusercontent.com/36275145/87290635-df568680-c51b-11ea-92d7-328220eb25a9.png)

**Comment by cmdcolin** [comment]
Can you make the screenshot from https://github.com/n3m3sis00/tree/issues/19#issuecomment-657103676 in a new comment
