### ISSUE TITLE
Use right angle drawing style for phylogeny tree

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#2]
Example

![image](https://user-images.githubusercontent.com/6511937/84796590-c44d3100-afc6-11ea-9488-8f457e006c59.png)

**Comment by n3m3sis00** [comment]
I tried to create the link in a straight-lined fashion rather than the default curvilinear. Here are the results.

### Screenshot
![](https://user-images.githubusercontent.com/34513489/85014308-a37e0a80-b183-11ea-88a5-156d3421ff79.png)

**Comment by cmdcolin** [comment]
Awesome, looks great
