### ISSUE TITLE
Fix rendering under Chrome?

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#3]

**Comment by n3m3sis00** [comment]
```javascript
tree_div: {
    border: 0,
    borderRadius: 3,
    boxShadow: '0 3px 5px 2px rgba(0, 0, 0, .3)',
    width: 'calc(100vw - 32px)'
  },
```
[Inspect](https://github.com/n3m3sis00/tree/commit/495e13e08784226a1f2ba44a17f03e7364115663#diff-9eb01088772bd513a186b131497d213bR17)

 Setting the tree_div width specifically resolved the issue.

**Comment by cmdcolin** [comment]
Looks like it was fixed!
