### ISSUE TITLE
Incorporate branch length into drawing

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#8]
The newick trees contain branch lengths, showing how distantly related certain branches of the tree are to the ancestors

Could incorporate this into the drawing

**Comment by n3m3sis00** [comment]
@cmdcolin Could you please elaborate about this, as I think it is already present in there (in drawing) as the coordinates of intersection point and leafs are directly related to distance.

**Comment by cmdcolin** [comment]
The checkbox "show branch length" here demonstrates the functionality. The branch length represents evolutionary distance https://bl.ocks.org/git-ashish/3aa81521f96e48198c80b4e2742bb6bc

**Comment by n3m3sis00** [comment]
I have tried to incorporate branch length into tree drawing here is the result.

### Screenshot
![myimage](https://user-images.githubusercontent.com/36275145/85953009-de095380-b98a-11ea-9941-ec3c928bda4a.gif)

**Comment by cmdcolin** [comment]
That looks great. Can you refactor it so the checkbox for the show branch length is outside of the tree component so the tree component is a pure drawing component.

**Comment by cmdcolin** [comment]
@n3m3sis00 from call today we discussed that maybe the scale factor needs some fixes. Feel free to close this issue when that is done though

**Comment by n3m3sis00** [comment]
```javascript

function maxLength(d) {
  return d.data.length + (d.children ? d3.max(d.children, maxLength) : 0)
}

function setBrLength(d, y0, k) {
  d.radius = (y0 += d.data.length) * k
  if (d.children)
    d.children.forEach(function (d) {
      setBrLength(d, y0, k)
    })
}
```
```javascript
 setBrLength(root, (root.data.length = 0), width / maxLength(root))
```

**Comment by cmdcolin** [comment]
From what I can tell this looks great!
