### ISSUE TITLE
Height adjustment not completely working for very large tree

### ISSUE THREAD

**Issue by cmdcolin** [n3m3sis00/tree#9]
I think our height fix isn't completely fixed. A large newick tree such as this goes off the screen

This is a COVID19 newick tree

https://github.com/hCoV-2019/lineages/blob/master/lineages/data/anonymised.aln.safe.fasta.treefile

**Comment by n3m3sis00** [comment]
* Currently, It is Working fine I create the this tree using the same data source please have a look

![img](https://user-images.githubusercontent.com/36275145/85854608-50830380-b7d2-11ea-8790-1709fe6875a4.png)

**Comment by cmdcolin** [comment]
Right on, not sure what I was seeing before
